language: generic

sudo: required
services:
  - docker

after_success:
  - docker build -f ./api/docker/Dockerfile -t hombrew/rtb-api:latest ./api
  - docker build -t hombrew/rtb-server:latest ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push hombrew/rtb-api
  - docker push hombrew/rtb-server
